server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions/ #positions.yaml

clients:
  - url: http://pgrafana.loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
    - targets:
        - localhost
      labels:
        job: varlogs
        __path__: /var/log/*.log

  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*.log # For linux only

    pipeline_stages:
      - docker: {}
      # - json:
      #     expressions:
      #       stream: stream
      #       attrs: attrs
      #       tag: attrs.tag
      #       time: time

      # - regex:
      #     expression: (?P<image_name>(?:[^|]*[^|])).(?P<container_name>(?:[^|]*[^|])).(?P<image_id>(?:[^|]*[^|])).(?P<container_id>(?:[^|]*[^|]))
      #     source: "tag"

      # - labels:
      #     tag:
      #     stream:
      #     image_name:
      #     container_name:
      #     image_id:
      #     container_id:

      # - timestamp:
      #     source: time
      #     format: RFC3339Nano

      # - match:
      #     # drop all logs for all containers that don't have --log-opt: tag="{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
      #     selector: '{job="docker",container_name="",image_name=""}'
      #     action: drop
